#!/usr/bin/env node
/**
 * Injects Vercel/build-time env vars into Angular production environment.
 * Usage: API_URL=https://your-api.onrender.com node scripts/set-env.js
 */
const fs = require('fs');
const path = require('path');

const apiUrl = process.env.API_URL || process.env.BACKEND_URL;

if (!apiUrl) {
  console.error(
    'Missing API_URL (or BACKEND_URL). Set it in Vercel → Settings → Environment Variables.',
  );
  process.exit(1);
}

const sanitized = apiUrl.replace(/\/$/, '').replace(/'/g, "\\'");
const target = path.join(__dirname, '../src/environments/environment.prod.ts');
const content = `// Auto-generated by scripts/set-env.js — do not edit in CI
export const environment = {
  production: true,
  apiUrl: '${sanitized}',
  graphqlUrl: '${sanitized}/graphql',
};
`;

fs.writeFileSync(target, content);
console.log(`Production environment configured: ${sanitized}`);
