#!/usr/bin/env node
/**
 * Writes Angular production environment for same-origin API proxy on Vercel.
 * Browser calls /api/* on the Vercel origin; vercel.json rewrites to Render.
 */
const fs = require('fs');
const path = require('path');

const target = path.join(__dirname, '../src/environments/environment.prod.ts');
const content = `// Auto-generated by scripts/set-env.js — do not edit in CI
export const environment = {
  production: true,
  apiUrl: '/api',
  graphqlUrl: '/api/graphql',
};
`;

fs.writeFileSync(target, content);
console.log('Production environment configured: /api (same-origin proxy)');
