// Auto-generated by scripts/set-env.js — do not edit in CI
export const environment = {
  production: true,
  apiUrl: 'https://todo-app-api-kcr1.onrender.com',
  graphqlUrl: 'https://todo-app-api-kcr1.onrender.com/graphql',
};
